#ifndef SM_NAMESPACE_H
#define SM_NAMESPACE_H

/* 0x00-0x2f are reserved by AbyssDB. Application keys start at 0x40. */
typedef enum sm_namespace_kind {
    SM_NS_SCHEMA_VERSION = 0x40,
    SM_NS_MIGRATION_STATE = 0x41,
    SM_NS_COUNTER = 0x42,
    SM_NS_SYSTEM_CONFIG = 0x43,

    SM_NS_EMPLOYEE_BY_ID = 0x50,
    SM_NS_EMPLOYEE_BY_ROLE = 0x51,
    SM_NS_EMPLOYEE_BY_STATUS = 0x52,

    SM_NS_PRODUCT_BY_ID = 0x60,
    SM_NS_PRODUCT_BY_BARCODE = 0x61,
    SM_NS_PRODUCT_BY_CATEGORY = 0x62,
    SM_NS_PRODUCT_BY_SUPPLIER = 0x63,
    SM_NS_PRODUCT_LOW_STOCK = 0x64,
    SM_NS_CATEGORY_BY_ID = 0x65,
    SM_NS_BATCH_BY_NO = 0x66,
    SM_NS_BATCH_BY_PRODUCT_EXPIRY = 0x67,
    SM_NS_BATCH_BY_PRODUCT_RECEIVED = 0x68,

    SM_NS_SUPPLIER_BY_ID = 0x70,
    SM_NS_SUPPLIER_BY_NAME = 0x71,
    SM_NS_SUPPLIER_FINANCE = 0x72,
    SM_NS_PAYABLE_BY_ID = 0x73,
    SM_NS_PAYABLE_BY_STATUS_DUE = 0x74,
    SM_NS_PAYABLE_BY_SUPPLIER = 0x75,
    SM_NS_PAYMENT_BY_ID = 0x76,
    SM_NS_PAYMENT_BY_PAYABLE = 0x77,
    SM_NS_PAYABLE_BY_PURCHASE = 0x78,

    SM_NS_MEMBER_BY_ID = 0x80,
    SM_NS_MEMBER_BY_PHONE = 0x81,
    SM_NS_MEMBER_BY_LEVEL = 0x82,
    SM_NS_MEMBER_CONSUME_BY_MEMBER = 0x83,
    SM_NS_VIP_CARD_BY_NO = 0x84,
    SM_NS_VIP_CARD_BY_MEMBER = 0x85,
    SM_NS_VIP_CARD_BY_STATUS = 0x86,
    SM_NS_VIP_TX_BY_CARD_TIME = 0x87,
    SM_NS_VIP_TX_BY_ID = 0x88,

    SM_NS_SALE_BY_ID = 0x90,
    SM_NS_SALE_ITEM_BY_SALE = 0x91,
    SM_NS_SALE_BY_STATUS = 0x92,
    SM_NS_SALE_BY_TIME = 0x93,
    SM_NS_SALE_BY_CASHIER_TIME = 0x94,
    SM_NS_SALE_BY_MEMBER_TIME = 0x95,

    SM_NS_STOCK_LOG_BY_ID = 0xa0,
    SM_NS_STOCK_LOG_BY_PRODUCT_TIME = 0xa1,
    SM_NS_STOCK_LOG_BY_TYPE_TIME = 0xa2,
    SM_NS_STORE_BY_ID = 0xa3,
    SM_NS_STORE_BY_NAME = 0xa4,
    SM_NS_STORE_STOCK = 0xa5,
    SM_NS_TRANSFER_BY_ID = 0xa6,
    SM_NS_TRANSFER_ITEM_BY_TRANSFER = 0xa7,
    SM_NS_TRANSFER_BY_STATUS = 0xa8,
    SM_NS_TRANSFER_BY_STORE = 0xa9,

    SM_NS_PURCHASE_BY_ID = 0xb0,
    SM_NS_PURCHASE_ITEM_BY_PURCHASE = 0xb1,
    SM_NS_PURCHASE_BY_STATUS = 0xb2,
    SM_NS_PURCHASE_BY_SUPPLIER_TIME = 0xb3,

    SM_NS_PROMOTION_BY_ID = 0xc0,
    SM_NS_PROMOTION_BY_PRODUCT = 0xc1,
    SM_NS_PROMOTION_BY_ACTIVE_TIME = 0xc2,
    SM_NS_COMBO_BY_ID = 0xc3,
    SM_NS_COMBO_ITEM_BY_COMBO = 0xc4,
    SM_NS_COMBO_BY_BARCODE = 0xc5,

    SM_NS_SCHEDULE_BY_ID = 0xd0,
    SM_NS_SCHEDULE_BY_EMPLOYEE_WEEK = 0xd1,
    SM_NS_SETTLEMENT_BY_ID = 0xd2,
    SM_NS_SETTLEMENT_BY_CASHIER_DATE = 0xd3,

    SM_NS_AUDIT_BY_ID = 0xe0,
    SM_NS_AUDIT_BY_TIME = 0xe1,
    SM_NS_AUDIT_BY_OPERATOR_TIME = 0xe2,
    SM_NS_AUDIT_BY_TYPE_TIME = 0xe3
} sm_namespace_kind;

#endif
